#!/usr/bin/env python3
"""Regenerates utils/aacgmGrid.ts: AACGM-v2 magnetic latitude over Australia
and New Zealand, at the height aurora is seen at.

    pip install aacgmv2
    python3 scripts/gen-aacgm-grid.py

Why a table: the auroral oval relations the app uses are fitted in corrected
geomagnetic coordinates, and over New Zealand those sit about 3.5 degrees
further from the equator than the simple tilted dipole says. AACGM itself is
a large spherical harmonic model, far too heavy to ship to a phone or paste
into a Worker, but over one region it is smooth enough that a one degree grid
with bilinear interpolation is good to about 0.002 degrees.

The field drifts by a few hundredths of a degree a year, so this wants
regenerating every few years, not every release.
"""

import datetime
import pathlib

import aacgmv2

EPOCH = datetime.datetime(2026, 7, 1)
HEIGHT_KM = 110          # the base of the aurora, where the oval relations apply
LAT0, LAT1 = -72, -25    # geographic, inclusive
LON0, LON1 = 110, 190    # degrees east, inclusive (190 = 170W, past the Chathams)

rows = []
for lat in range(LAT0, LAT1 + 1):
    row = []
    for lon in range(LON0, LON1 + 1):
        mlat = aacgmv2.get_aacgm_coord(lat, ((lon + 180) % 360) - 180, HEIGHT_KM, EPOCH)[0]
        if mlat != mlat:  # NaN
            raise SystemExit(f'AACGM undefined at {lat}, {lon}')
        row.append(round(mlat * 100))
    rows.append(row)

body = ',\n'.join('  ' + ','.join(str(v) for v in row) for row in rows)
out = f"""// Generated by scripts/gen-aacgm-grid.py - do not edit by hand.
//
// AACGM-v2 magnetic latitude in hundredths of a degree, {HEIGHT_KM} km altitude,
// epoch {EPOCH.date().isoformat()}. Rows run from {LAT0} to {LAT1} degrees geographic
// latitude, columns from {LON0} to {LON1} degrees east, one degree apart.

export const AACGM_GRID = {{
  lat0: {LAT0},
  lon0: {LON0},
  rows: {len(rows)},
  cols: {len(rows[0])},
  heightKm: {HEIGHT_KM},
  epoch: '{EPOCH.date().isoformat()}',
  values: [
{body},
  ],
}};
"""
path = pathlib.Path(__file__).resolve().parent.parent / 'utils' / 'aacgmGrid.ts'
path.write_text(out)
print(f'wrote {path} ({len(rows)} x {len(rows[0])})')
