# Configuration for your main application (you likely already have this)
name = "basic---to-go-live-nasa-cme-modeler"
main = "src/index.tsx" # Or whatever your main entry point is
compatibility_date = "2024-03-20"
# ... other configurations for your main app

# [[workers_dev]]
# Your main worker dev config

# --- ADD THIS NEW WORKER CONFIGURATION ---
[[workers]]
name = "sdo-image-proxy" # You can name this whatever you like
main = "image-proxy/index.ts"
compatibility_date = "2024-03-20"